execute pathogen#infect()

set t_Co=256
colors wombat256mod 
let macvim_skip_colorscheme=1

set novisualbell "Не мигать 
set noerrorbells
set encoding=utf-8 "Кодировка файлов по умолчанию
set nobackup
set noswapfile
set ffs=unix,dos

"Hack for copy paste and paste again problem"
xnoremap p pgvy
"Degradate vim for speed improve
set fillchars=diff:⣿,vert:│
"set fillchars=diff:⣿,vert:\|

" ----------------------------------------------------------------------------
"  Text Formatting
" ----------------------------------------------------------------------------

set autoindent             " automatic indent new lines
set smartindent            " be smart about it
set nowrap                 " do not wrap lines
set softtabstop=2          " yep, two
set shiftwidth=2           " ..
set tabstop=4
set expandtab              " expand tabs to spaces
set nosmarttab             " fuck tabs
set formatoptions+=n       " support for numbered/bullet lists
"set textwidth=80           " wrap at 80 chars by default
set virtualedit=block      " allow virtual edit in visual block ..

" Folder
set foldenable
set foldlevelstart=10
set foldnestmax=10 
set foldmethod=indent
"set cursorline          " highlight current line"
set wildignore=*.swp,*.bak,*.pyc,*.class

set laststatus=2
set statusline=
set statusline+=%f         " Path to the file
set statusline+=\ 
set statusline+=%{exists('g:loaded_fugitive')?fugitive#statusline():''}
set statusline+=%=        " Switch to the right side
set statusline+=%=%-10.(%c%V%)  " Right aligned file nav info"
set statusline+=\ 
set statusline+=%l        " Current line
set statusline+=/         " Separator
set statusline+=%L        " Total lines

" ----------------------------------------------------------------------------
"  Remapping
" ----------------------------------------------------------------------------

" lead with ,
let mapleader = ","

set pastetoggle=<Leader>p "hack for copy code
nmap <Leader>o :TagbarToggle<CR>

" exit to normal mode with 'jj'
inoremap jj <ESC>


" reflow paragraph with Q in normal and visual mode
nnoremap Q gqap
vnoremap Q gq

" sane movement with wrap turned on
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

" cool NERDTree open/close
map ,m :NERDTree<cr>

" launch unit tests
map <Leader>u :!nosetests<cr>
" search 
map <leader>a :Ack 

" Use 'extra magic' for regex searches
nnoremap <space> ?
vnoremap <space> ?

" Switch between the last two files
nnoremap <space><space> <c-^>
nnoremap <leader><space> :GitGutterToggle<cr>

" коментирование - ракоментирования текста
map <C-K> <leader>c<space>

"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
"inoremap <up> <nop>
"inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>

" arrow keys -> window resize
nnoremap <left> :vertical resize -5<cr>
nnoremap <down> :resize +5<cr>
nnoremap <up> :resize -5<cr>
nnoremap <right> :vertical resize +5<cr>

au FocusLost * :wa

" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv

" Same when jumping around
nnoremap g; g;zz
nnoremap g, g,zz
nnoremap ]] ]]zt
nnoremap [[ [[zt
nnoremap <c-o> <c-o>zz
nnoremap <c-i> <c-i>zz
nnoremap <c-t> <c-t>zt

" ----------------------------------------------------------------------------
"  UI
" ----------------------------------------------------------------------------

"set ruler                  " show the cursor position all the time
set noshowcmd              " don't display incomplete commands
set nolazyredraw           " turn off lazy redraw
set number                 " line numbers
set wildmenu               " turn on wild menu
set wildmode=list:longest
set ch=2                   " command line height
set backspace=2            " allow backspacing over everything in insert mode
set whichwrap+=<,>,h,l,[,] " backspace and cursor keys wrap to
set shortmess=filtIoOA     " shorten messages
set report=0               " tell us about changes
set nostartofline          " don't jump to the start of line when scrolling
set completeopt=menu,menuone,longest
set pumheight=15
"set lazyredraw
"set ttyfast
let loaded_matchparen=1 " Don't load matchit.vim (paren/bracket matching)
set noshowmatch         " Don't match parentheses/brackets
"set nocursorline        " Don't paint cursor line
set nocursorcolumn      " Don't paint cursor column
"set scrolljump=8        " Scroll 8 lines at a time at bottom/top
let html_no_rendering=1 " Don't render italic, bold, links in HTML"

" ----------------------------------------------------------------------------
" Visual Cues
" ----------------------------------------------------------------------------

set showmatch              " brackets/braces that is
set mat=5                  " duration to show matching brace (1/10 sec)
set incsearch              " do incremental searching
set laststatus=2           " always show the status line
set ignorecase             " ignore case when searching
set nohlsearch             " don't highlight searches

" ---------------------------------------------------------------------------
"  Strip all trailing whitespace in file
" ---------------------------------------------------------------------------

function! StripWhitespace ()
    exec ':%s/ \+$//gc'
endfunction
map ,s :call StripWhitespace ()<CR>

" Emmete Ctrl E"
let g:user_emmet_leader_key='<C-E>'
" set the bundle root, and vundle directory
let root = '~/.vim/bundle'
let src = 'http://github.com/gmarik/vundle.git'

" clone vundle if it's missing
if !isdirectory(expand(root, 1).'/vundle')
  exec '!git clone '.src.' '.shellescape(expand(root.'/vundle', 1))
endif

" immediately make vundle accessible in the rtp
exec 'set rtp+='.root.'/vundle'

" initialise vundle's boot script
call vundle#rc(root)

set autowrite " vaxe likes autowrite
set nocompatible " we need fancy new vim 7.0 features
syntax enable on " turn on syntax highlighting

" This disables the preview window for function completions.
" This window can get distracting, so I often just turn it off.
" set completeopt=menuone

filetype off " turn off filetype settings, which is required for vundle

Bundle 'gmarik/vundle'
Bundle 'gcmt/tube.vim'
Bundle 'jdonaldson/vaxe'
Bundle 'plasticboy/vim-markdown'
Bundle 'Raimondi/delimitMate'
Bundle 'tpope/vim-fugitive'
Bundle 'gregsexton/gitv'
Bundle 'majutsushi/tagbar'
Bundle 'mattn/emmet-vim'
Bundle 'vim-scripts/ZoomWin'
Bundle 'tpope/vim-surround'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
"Bundle "garbas/vim-snipmate"
Bundle "SirVer/ultisnips"
Bundle "honza/vim-snippets"
Bundle 'lunaru/vim-less'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdtree'
Bundle 'croaky/vim-colors-github'
Bundle 'Valloric/YouCompleteMe'
Bundle 'mileszs/ack.vim'
Bundle 'jgdavey/tslime.vim'
Bundle 'rstacruz/sparkup'
Bundle 'JulesWang/css.vim'
Bundle 'cakebaker/scss-syntax.vim'
Bundle 'nono/vim-handlebars'
Bundle 'kien/ctrlp.vim'
Bundle 'ivalkeen/vim-ctrlp-tjump'
Bundle 'Rykka/colorv.vim'
Bundle 'benmills/vimux'
Bundle 'airblade/vim-gitgutter'
Bundle 'editorconfig/editorconfig-vim'
Bundle 'rizzatti/dash.vim'
"Bundle 'yonchu/accelerated-smooth-scroll'
"Bundle 'bling/vim-airline'
"Bundle 'chriskempson/base16-vim'

let g:clang_complete_auto = 0
" Show clang errors in the quickfix window
let g:clang_complete_copen = 1
"let g:cland_auto_select = 0

filetype plugin indent on " re-enable plugin settings

"filetype plugin on
"set omnifunc=syntaxcomplete#Complete
" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags


" force write a file
cmap w!! w !sudo tee % >/dev/null

let g:snips_author = "Yura Zatsepin"
let g:snips_email = "yura.zatsepin@gmail.com"
let g:snips_github = "Partysun"

let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

"let g:jedi#goto_assignments_command = "<leader>g"
"let g:jedi#goto_definitions_command = "<leader>d"
"let g:jedi#documentation_command = "K"
"let g:jedi#usages_command = "<leader>n"
"let g:jedi#rename_command = "<leader>r"
"let g:jedi#show_call_signatures = "1"
" Hack for SuperTab supprot with YouCompleteMe
"let g:ycm_key_list_select_completion = ['<Down>']
"let g:ycm_autoclose_preview_window_after_completion=1
"let g:ycm_path_to_python_interpreter = '/usr/local/bin/python'
let g:ackprg = 'ag --nogroup --nocolor --column'
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
" Use ag over grep
set grepprg=ag\ --nogroup\ --nocolor

"----------------------------------------
" Use ag in CtrlP for listing files. Lightning fast and respects
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
" ag is fast enough that CtrlP doesn't need to cache
let g:ctrlp_use_caching = 0
nnoremap <leader>. :CtrlPTag<cr>
"set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc     " MacOSX/Linux
"set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
"let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$\|\.log$\|\.pyc$\'
"let g:ctrlp_custom_ignore = '\v[\/]\.(DS_Storegit|hg|svn|optimized|compiled|node_modules|pyc)$'
let g:ctrlp_custom_ignore = {'file': '\v(\.cpp|\.h|\.pyc|\.hh|\.cxx)@<!$'}
"-----------------------------------------

" Haxe helpers
let g:vaxe_openfl_target = "flash"
let g:vaxe_lime_target = "flash"
let g:vaxe_haxe_version = 3
let g:vaxe_completion_write_compiler_output = 1
map <Leader>oh :call vaxe#OpenHxml()<CR>
map <Leader>ct :call vaxe#Ctags()<CR>
map <Leader>ic :call vaxe#ImportClass()<CR>
map <Leader>pj :call vaxe#ProjectHxml()<CR>
map <Leader>gd :call vaxe#JumpToDefinition()<CR>

" Tube settings
let g:tube_terminal = "iterm"
nnoremap <Leader>e :TubeFocus

" Disable GitGutter
let g:gitgutter_enabled = 0

" CTRLP extensions
nnoremap <c-]> :CtrlPtjump<cr>
vnoremap <c-]> :CtrlPtjumpVisual<cr>
nnoremap <Leader>.l :CtrlPLine<CR>

" ,b
" In Visual mode exec git blame with selected text
vmap <Leader>b :<C-U>!git blame <C-R>=expand("%:p") <CR> \|sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>"

vmap <C-c><C-c> <Plug>SendSelectionToTmux
nmap <C-c><C-c> <Plug>NormalModeSendToTmux
nmap <C-c>r <Plug>SetTmuxVars

" allows cursor change in tmux mode
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

let NERDTreeHijackNetrw=1
" Don't display these kinds of files
let NERDTreeIgnore=[ '\.pyc$', '\.pyo$', '\.py\$class$', '\.obj$',
    \ '\.o$', '\.so$', '\.egg$', '^\.git$', '\.svn$',
    \ '__pycache__', '\.egg-info$', '\.hg$', '\.cibox$']"

"nnoremap <leader>e :call VimuxRunCommand("make test")<CR>

set tags+=/usr/lib/haxe/lib/flixel/git/.git/tags
set tags+=/usr/lib/haxe/lib/flixel-addons/git/.git/tags
set tags+=/usr/lib/haxe/lib/flixel-ui/git/.git/tags
set tags+=/usr/lib/haxe/lib/spinehaxe/git/.git/tags
