execute pathogen#infect()

set t_Co=256
colors wombat256mod

set novisualbell "Не мигать 
set noerrorbells
set encoding=utf-8 "Кодировка файлов по умолчанию
set nobackup
set noswapfile
set ffs=unix,dos

" ----------------------------------------------------------------------------
"  Text Formatting
" ----------------------------------------------------------------------------

set autoindent             " automatic indent new lines
set smartindent            " be smart about it
set nowrap                 " do not wrap lines
set softtabstop=2          " yep, two
set shiftwidth=2           " ..
set tabstop=4
set expandtab              " expand tabs to spaces
set nosmarttab             " fuck tabs
set formatoptions+=n       " support for numbered/bullet lists
"set textwidth=80           " wrap at 80 chars by default
set virtualedit=block      " allow virtual edit in visual block ..

" ----------------------------------------------------------------------------
"  Remapping
" ----------------------------------------------------------------------------

" lead with ,
let mapleader = ","

set pastetoggle=<Leader>p "hack for copy code
nmap <Leader>o :TagbarToggle<CR>

" exit to normal mode with 'jj'
inoremap jj <ESC>


" reflow paragraph with Q in normal and visual mode
nnoremap Q gqap
vnoremap Q gq

" sane movement with wrap turned on
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

" cool NERDTree open/close
map ,n :NERDTree<cr>

" launch unit tests
map ,u :!sh ci.sh<cr>

" Use 'extra magic' for regex searches
nnoremap <space> ?
vnoremap <space> ?

" Switch between the last two files
nnoremap <space><space> <c-^>

" ----------------------------------------------------------------------------
"  UI
" ----------------------------------------------------------------------------

set ruler                  " show the cursor position all the time
set noshowcmd              " don't display incomplete commands
set nolazyredraw           " turn off lazy redraw
set number                 " line numbers
set wildmenu               " turn on wild menu
set wildmode=list:longest
set ch=2                   " command line height
set backspace=2            " allow backspacing over everything in insert mode
set whichwrap+=<,>,h,l,[,] " backspace and cursor keys wrap to
set shortmess=filtIoOA     " shorten messages
set report=0               " tell us about changes
set nostartofline          " don't jump to the start of line when scrolling
set completeopt=menu,menuone,longest
set pumheight=15
let g:SuperTabDefaultCompletionType = "context"
set lazyredraw

" ----------------------------------------------------------------------------
" Visual Cues
" ----------------------------------------------------------------------------

set showmatch              " brackets/braces that is
set mat=5                  " duration to show matching brace (1/10 sec)
set incsearch              " do incremental searching
set laststatus=2           " always show the status line
set ignorecase             " ignore case when searching
set nohlsearch             " don't highlight searches

" ---------------------------------------------------------------------------
"  Strip all trailing whitespace in file
" ---------------------------------------------------------------------------

function! StripWhitespace ()
    exec ':%s/ \+$//gc'
endfunction
map ,s :call StripWhitespace ()<CR>


" set the bundle root, and vundle directory
let root = '~/.vim/bundle'
let src = 'http://github.com/gmarik/vundle.git'

" clone vundle if it's missing
if !isdirectory(expand(root, 1).'/vundle')
  exec '!git clone '.src.' '.shellescape(expand(root.'/vundle', 1))
endif

" immediately make vundle accessible in the rtp
exec 'set rtp+='.root.'/vundle'

" initialise vundle's boot script
call vundle#rc(root)

set autowrite " vaxe likes autowrite
set nocompatible " we need fancy new vim 7.0 features
syntax enable on " turn on syntax highlighting

" This disables the preview window for function completions.
" This window can get distracting, so I often just turn it off.
" set completeopt=menuone

filetype off " turn off filetype settings, which is required for vundle

Bundle 'gmarik/vundle'
" load vaxe, and neocomplcache with the given config"
Bundle 'jdonaldson/vaxe'
"Bundle 'Shougo/neocomplcache'
Bundle 'Raimondi/delimitMate'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle 'tpope/vim-fugitive'
Bundle 'majutsushi/tagbar'
Bundle 'mattn/emmet-vim'
Bundle 'vim-scripts/ZoomWin'
Bundle 'tpope/vim-surround'
Bundle "tomtom/tlib_vim"
Bundle 'ervandew/supertab'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"
Bundle 'lunaru/vim-less'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdtree'
Bundle 'croaky/vim-colors-github'
Bundle 'Valloric/YouCompleteMe'
Bundle 'davidhalter/jedi-vim'
Bundle 'mileszs/ack.vim'
"Bundle 'mhinz/vim-startify'
"undle 'Lokaltog/powerline', {'rtp':'powerline/bindings/vim'}
"/Bundle 'zhaocai/linepower.vim'
"let g:neocomplcache_enable_at_startup = 1 " always load neocc
"let g:neocomplcache_enable_auto_select = 1 " auto-popup!
"if !exists('g:neocomplcache_omni_patterns')
    "let g:neocomplcache_omni_patterns = {} " set a default pattern dict
"endif
" Disable auto popup, use <Tab> to autocomplete
let g:clang_complete_auto = 0
" Show clang errors in the quickfix window
let g:clang_complete_copen = 1
"let g:cland_auto_select = 0

"" this tells neocc when to try for completions... after '.', '(', etc.
"let g:neocomplcache_omni_patterns.haxe = '\v([\]''"\)]|\w|(^\s*))(\.|\()'

filetype plugin indent on " re-enable plugin settings

"filetype plugin on
"set omnifunc=syntaxcomplete#Complete
" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

nnoremap <Leader>e :make flash<CR>

" force write a file
cmap w!! w !sudo tee % >/dev/null

let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = "<leader>d"
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#rename_command = "<leader>r"
let g:jedi#show_call_signatures = "1"
" Hack for SuperTab supprot with YouCompleteMe
let g:ycm_key_list_select_completion = ['<Down>']
let g:ycm_autoclose_preview_window_after_completion=1
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
let g:vaxe_nme_target = "mac"

" ,b
" In Visual mode exec git blame with selected text
vmap <Leader>b :<C-U>!git blame <C-R>=expand("%:p") <CR> \|sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>"
