alias reload!='. ~/.zshrc'
alias ll="ls -al"
alias rmpyc="find . -name '*.pyc' -delete"    # Remove .PYC files.
alias dj='python manage.py'
alias df="df -h" # Disk free, in gigabytes, not bytes
alias du="du -h -c"   # Calculate total disk usage for a folder
alias ..="cd .."                              # Go up one directory
alias ...="cd ../.."                          # Go up two directories
alias ci="ssh yura@serafim.cloudapp.net" # Connect Serafim server
