working_directory = "none"

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
thickness = 0.35

[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 18

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "zellij"
args = ["-l", "welcome"]

[window]
decorations = "Full"
opacity = 0.85
title = "Code"
startup_mode = "Fullscreen"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10
